# Generated by Django 2.2.3 on 2019-07-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
