# Generated by Django 2.2.3 on 2019-07-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190710_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=400),
        ),
    ]
