# Generated by Django 2.2.3 on 2019-07-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190726_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
