# Generated by Django 2.2.3 on 2019-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190726_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='images/default.jpg', max_length=400, upload_to='images/'),
        ),
    ]
