# Generated by Django 2.2.3 on 2019-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20190727_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='images/default.jpg', max_length=400, upload_to='images/%Y/%m/%d/'),
        ),
    ]
