# Generated by Django 2.2.3 on 2019-07-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190727_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(max_length=400, upload_to='images/'),
        ),
    ]
